[package]
name = "fatty_scheduler"
version = "0.1.1"
authors = ["Mateusz Dahlke <1i13i.dahlke@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
